# Application name
spring.application.name=user-service

# Server port
server.port=8082

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tallydb
spring.datasource.username=postgres
spring.datasource.password=tally123

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show detailed errors
server.error.include-message=always

# MTN MoMo Sandbox
momo.subscription.key=69d64a44de7b47c89e8d64655d3f2483
momo.api.user=6c3e4b5a-2d1f-4e8a-9b7c-0d5e6f7a8b9c
momo.api.key=fb794d3442e94dd7a2ffc08d6992420e
momo.base.url=https://sandbox.momodeveloper.mtn.com
momo.environment=sandbox
momo.currency=EUR
momo.callback.url=http://localhost:8082/api/momo/callback